// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIP_FCkI0lWQrxpUIv2r7toBjjT-ItKGI',
    appId: '1:605853593806:web:c617514fad4add0496e09f',
    messagingSenderId: '605853593806',
    projectId: 'fir-bbd72',
    authDomain: 'fir-bbd72.firebaseapp.com',
    storageBucket: 'fir-bbd72.appspot.com',
    measurementId: 'G-XP2341QYQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSXIoBB-5NDirm7U2QTfP-hFoeh73Eqk',
    appId: '1:605853593806:android:0cddd5d1a3ae09be96e09f',
    messagingSenderId: '605853593806',
    projectId: 'fir-bbd72',
    storageBucket: 'fir-bbd72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiCib8QsEw9zrCyzvTUn5FSaV7dUHuUM',
    appId: '1:605853593806:ios:bd26b0a804ae6fc096e09f',
    messagingSenderId: '605853593806',
    projectId: 'fir-bbd72',
    storageBucket: 'fir-bbd72.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqiCib8QsEw9zrCyzvTUn5FSaV7dUHuUM',
    appId: '1:605853593806:ios:1a386ded50949d0596e09f',
    messagingSenderId: '605853593806',
    projectId: 'fir-bbd72',
    storageBucket: 'fir-bbd72.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
